# api config
APP_API_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3005,https://api.d02.teba-saki.net"
APP_API_BASE_URL: "https://api.d02.teba-saki.net"

# lambda powertools config
POWERTOOLS_SERVICE_NAME: "api-dev"
POWERTOOLS_LOG_LEVEL: "DEBUG"
POWERTOOLS_DEV: false
POWERTOOLS_DEBUG: false
POWERTOOLS_TRACE_MIDDLEWARES: true
POWERTOOLS_TRACE_DISABLED: true
