# api config
APP_API_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3005"
APP_API_BASE_URL: "http://localhost:3333"

# lambda powertools config
POWERTOOLS_SERVICE_NAME: "api-local"
POWERTOOLS_LOG_LEVEL: "DEBUG"
POWERTOOLS_DEV: true
POWERTOOLS_DEBUG: true
POWERTOOLS_TRACE_MIDDLEWARES: true
POWERTOOLS_TRACE_DISABLED: true

# VPC config
APIGW_VPC_ENDPOINT_ID: "vpce-083e353684e87715f" # gsp-test-sbr-vpce-apigateway
